name: Deploy website on push new tag

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [ 8.1 ]

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Restore the Composer cache directory
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-'8.0'-composer-

      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          dev: no
          args: --prefer-dist --no-interaction

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: website/app/languages

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: remove old Symlink
        run: ssh ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} -vvv "unlink ~/code/shared/"

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: app

      - name: Deploy with rsync
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avzr --delete
          run: ls -la
          path: .
          remote_path: ~/code/deploy
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_key: ${{ secrets.DEPLOY_KEY }}

      - name: remove old Symlink
        run: ssh ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} -vvv "ln -s ~/code/shared/ ~/code/deploy"